import './globals.css'
import { Inter } from 'next/font/google'
import Futurama from './components/Futurama';
import AboutUs from './components/AboutUs';
import Skills from './components/Skills';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

       <Futurama />
        <AboutUs />
        <Skills />
        
        {children}</body>
    </html>
  )
}
